repos:
  - repo: local
    hooks:
      - id: buildifier
        name: Format Bazel files with buildifier
        description: Formats all Bazel files recursively using buildifier -r and stages changes
        entry: ./.buildifier-recursive-hook.sh
        language: system
        pass_filenames: false
        always_run: true