"""CMake configure_file rule for Bazel that uses cmake binary for file generation."""

def _cmake_configure_file_impl(ctx):
    """Implementation of cmake_configure_file rule that calls cmake binary."""
    input_file = ctx.file.src
    output_file = ctx.outputs.out
    cmake_binary = ctx.executable.cmake_binary
    
    # Validate inputs
    if not input_file:
        fail("src attribute is required")
    if not output_file:
        fail("out attribute is required")
    if not cmake_binary:
        fail("cmake_binary attribute is required. Please provide a cmake binary target, e.g.: cmake_binary = \"@cmake//:cmake\"")
    
    # Validate variable values for shell safety
    for key, value in ctx.attr.defines.items():
        if not key:
            fail("Empty variable name found in defines")
        if '"' in value or "'" in value:
            fail("Variable value for '%s' contains quotes which could be unsafe: %s" % (key, value))
        if "$" in value and not value.startswith("${") and not value.endswith("}"):
            fail("Variable value for '%s' contains unescaped $ which could be unsafe: %s" % (key, value))
    
    # Create a temporary CMakeLists.txt file that performs the configure_file operation
    cmake_script = ctx.actions.declare_file(ctx.label.name + "_configure.cmake")
    
    # Build cmake -D arguments for variable definitions
    define_args = []
    for key, value in ctx.attr.defines.items():
        # Escape value for command line safety
        escaped_value = value.replace("\\", "\\\\").replace('"', '\\"')
        define_args.append('-D%s="%s"' % (key, escaped_value))
    
    # Create CMake script content with proper escaping
    script_content = "# CMake configure_file script generated by Bazel\n"
    script_content += "# Set variables\n"
    for key, value in ctx.attr.defines.items():
        # Escape value for CMake script
        escaped_value = value.replace("\\", "\\\\").replace('"', '\\"')
        script_content += 'set(%s "%s")\n' % (key, escaped_value)
    
    script_content += '''
# Validate that required variables are set
if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE not defined")
endif()
if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE not defined")
endif()

# Check that input file exists
if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input file does not exist: ${INPUT_FILE}")
endif()

# Configure the file
configure_file("${INPUT_FILE}" "${OUTPUT_FILE}" @ONLY)

# Verify output file was created
if(NOT EXISTS "${OUTPUT_FILE}")
    message(FATAL_ERROR "Failed to create output file: ${OUTPUT_FILE}")
endif()
'''
    
    # Write the CMake script
    ctx.actions.write(
        output = cmake_script,
        content = script_content,
    )
    
    # Run cmake in script mode to perform the configure_file operation
    ctx.actions.run(
        inputs = [input_file, cmake_script],
        outputs = [output_file],
        executable = cmake_binary,
        arguments = [
            "-DINPUT_FILE=" + input_file.path,
            "-DOUTPUT_FILE=" + output_file.path,
        ] + define_args + [
            "-P", cmake_script.path,
        ],
        mnemonic = "CMakeConfigureFile",
        progress_message = "Configuring %s with cmake" % output_file.short_path,
        use_default_shell_env = False,  # Use controlled environment
    )
    
    return [DefaultInfo(files = depset([output_file]))]

cmake_configure_file = rule(
    implementation = _cmake_configure_file_impl,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The input template file to configure",
        ),
        "out": attr.output(
            mandatory = True,
            doc = "The output file to generate",
        ),
        "defines": attr.string_dict(
            default = {},
            doc = "Dictionary of variable definitions for substitution",
        ),
        "cmake_binary": attr.label(
            executable = True,
            cfg = "exec",
            doc = "The cmake binary to use for file configuration. Required for rule execution.",
            allow_single_file = True,
        ),
    },
    doc = "Configures a file using cmake binary, similar to CMake's configure_file command.",
)