name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  plugin-tests:
    name: Plugin Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelrc: ${{ secrets.BUILDBUDDY_BAZELRC }}

      - name: Run Go tests
        run: bazel test //...

  example-libzmq:
    name: "Example: libzmq"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelrc: ${{ secrets.BUILDBUDDY_BAZELRC }}

      - name: "Build Example: libzmq"
        run: |
          bazel run //:gazelle
          bazel build //libzmq:all
        working-directory: examples

  example-librdkafka:
    name: "Example: librdkafka"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelrc: ${{ secrets.BUILDBUDDY_BAZELRC }}

      - name: "Build Example: librdkafka"
        run: |
          bazel run //:gazelle
          bazel build //thirdparty/librdkafka:all
        working-directory: examples
