name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0

      - name: Verify Bazel module integrity
        run: |
          bazel mod tidy
          cd examples
          bazel mod tidy

      - name: Run Go tests
        run: bazel test //...

      - name: Build gazelle-foreign-cc plugin
        run: bazel build //cmd/gazelle-foreign-cc:gazelle

      - name: Generate and build examples
        run: |
          bazel run //:gazelle
          bazel build //...
        working-directory: ${{ github.workspace }}/examples
