name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.14.0

      - name: Verify Bazel module integrity
        run: |
          bazel mod tidy
          cd examples
          bazel mod tidy

      - name: Run Go tests
        run: bazel test //...

      - name: Build gazelle-foreign-cc plugin
        run: bazel build //cmd/gazelle-foreign-cc:gazelle

      - name: Generate and build examples
        run: |
          PLUGIN_PATH_DIR=$(mktemp -d)
          cp bazel-bin/gazelle/gazelle-foreign-cc_/gazelle-foreign-cc $PLUGIN_PATH_DIR/gazelle-cmake
          export PATH=$PLUGIN_PATH_DIR:$PATH
          bazel build @gazelle//cmd/gazelle
          cd examples
          ../bazel-bin/external/gazelle+/cmd/gazelle/gazelle_/gazelle .
          bazel build //...
        env:
          BUILD_WORKSPACE_DIRECTORY: ${{ github.workspace }}/examples
